apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prueba-devops-ingress
  namespace: devops-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: prueba-devops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prueba-devops-service
                port:
                  number: 80
