apiVersion: v1
kind: Service
metadata:
  name: prueba-devops-service
  namespace: devops-demo
spec:
  type: ClusterIP
  selector:
    app: prueba-devops
  ports:
    - port: 80
      targetPort: 3000
